apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-example
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  labels:
    run: api-example
spec:
  rules:
  - host: api-example.gruposfa.com.br
    http:
      paths:
      - backend:
          serviceName: api-example
          servicePort: 80
