spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        jdbc-url: jdbc:sqlserver://srv-mssql-hml:1433;databasename=SFANovo
        username: novo
        password: N0v0@t@c@rej0
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        hibernate:
            ddl-auto: none
    properties:
        hibernate:
            show_sql: true
            use_sql_comments: true
            format_sql: true
server:
    port: 8080             
 